spring.application.name=gateway

server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ========== RUTAS A MICROSERVICIOS ==========
# Usuarios
spring.cloud.gateway.routes[0].id=usuarios
spring.cloud.gateway.routes[0].uri=lb://ms-usuarios
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

# Catalogo
spring.cloud.gateway.routes[1].id=catalogo
#--EL NOMBRE DE APLICATION.NAME TIENE QUE ESER IGUAL AL URI TIPO ms-catalogos
spring.cloud.gateway.routes[1].uri=lb://ms-catalogo  
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/productos/**,/api/categorias/**

# Inventario
spring.cloud.gateway.routes[2].id=inventario
spring.cloud.gateway.routes[2].uri=lb://ms-inventario
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/stock/**,/api/almacenes/**

# Carrito
spring.cloud.gateway.routes[3].id=carrito
spring.cloud.gateway.routes[3].uri=lb://ms-carrito
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/carrito/**

# Pedido
spring.cloud.gateway.routes[4].id=pedido
spring.cloud.gateway.routes[4].uri=lb://ms-pedido
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/pedidos/**

# Pago
spring.cloud.gateway.routes[5].id=pago
spring.cloud.gateway.routes[5].uri=lb://ms-pago
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/pagos/**

# Reseñas
spring.cloud.gateway.routes[6].id=resenas
spring.cloud.gateway.routes[6].uri=lb://ms-resenas
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/resenas/**

# Storage
spring.cloud.gateway.routes[7].id=storage
spring.cloud.gateway.routes[7].uri=lb://ms-storage
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/archivos/**


# Facturacion OPCIONAL--Si se alcanza a implementar
#--spring.cloud.gateway.routes[8].id=facturacion
#spring.cloud.gateway.routes[8].uri=lb://ms-facturacion
#spring.cloud.gateway.routes[8].predicates[0]=Path=/api/documentos/**

