spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: usuarios
              uri: lb://ms-usuarios
              predicates:
                - Path=/api/usuarios/**
            - id: catalogo
              uri: lb://ms-catalogo
              predicates:
                - Path=/api/productos/**,/api/categorias/**
            - id: inventario
              uri: lb://ms-inventario
              predicates:
                - Path=/api/stock/**,/api/almacenes/**
            - id: carrito
              uri: lb://ms-carrito
              predicates:
                - Path=/api/carrito/**
            - id: pedido
              uri: lb://ms-pedido
              predicates:
                - Path=/api/pedidos/**
            - id: pago
              uri: lb://ms-pago
              predicates:
                - Path=/api/pagos/**
            - id: resenas
              uri: lb://ms-resenas
              predicates:
                - Path=/api/resenas/**
            - id: storage
              uri: lb://ms-storage
              predicates:
                - Path=/api/archivos/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 12345678901234567890123456789012345678901234567890
  expiration: 86400000